### PR TITLE
fix(tests): restrict 'cat' tests to unix environments. Fixes #776

### LINKED ISSUE #776: Inconsistent behavior of Integration tests using `cat` on Windows
The following tests (in `tests/integration_tests.rs`) have issues in Windows: 
1. `can_pass_input_to_command_from_a_file` - fails, 
2. `fails_if_invalid_stdin_data_file_provided` - passes, but false positive due to assertion.

Reason:  The use of `cat` command (supported in unix-like environments)
OS: Windows 11

<br />

logs:
```
---- can_pass_input_to_command_from_a_file stdout ----
thread 'can_pass_input_to_command_from_a_file' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
\'cat\' is not recognized as an internal or external command,\r
operable program or batch file.\r
Error: Command terminated with non-zero exit code 1 in the first benchmark run. Use the \'-i\'/\'--ignore-failure\' option if you want to ignore this. Alternatively, use the \'--show-output\' option to debug what went wrong.
```
```
command=`"C:\\Users\\ritvikos\\Desktop\\OSS\\hyperfine\\target\\debug\\hyperfine.exe" "--runs=1" "--input=example_input_file.txt" "--show-output" "cat"`
code=1
stdout="Benchmark 1: cat\n"
stderr=```
\'cat\' is not recognized as an internal or external command,\r
operable program or batch file.\r
Error: Command terminated with non-zero exit code 1 in the first benchmark run. Use the \'-i\'/\'--ignore-failure\' option if you want to ignore this. Alternatively, use the \'--show-output\' option to debug what went wrong.
```

<br />

Stack Backtrace:
```
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: core::panicking::panic_display<assert_cmd::assert::AssertError>
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\panicking.rs:264
   3: assert_cmd::assert::impl$35::panic::panic_cold_display<assert_cmd::assert::AssertError>
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\panic.rs:100
   4: assert_cmd::assert::AssertError::panic<assert_cmd::assert::Assert>
             at C:\Users\ritvikos\.cargo\registry\src\index.crates.io-6f17d22bba15001f\assert_cmd-2.0.16\src\assert.rs:1033
   5: core::ops::function::FnOnce::call_once<assert_cmd::assert::Assert (*)(assert_cmd::assert::AssertError),tuple$<assert_cmd::assert::AssertError> >
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:250
   6: enum2$<core::result::Result<assert_cmd::assert::Assert,assert_cmd::assert::AssertError> >::unwrap_or_else<assert_cmd::assert::Assert,assert_cmd::assert::AssertError,assert_cmd::assert::Assert (*)(assert_cmd::assert::AssertError)>
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\result.rs:1456
   7: assert_cmd::assert::Assert::success
             at C:\Users\ritvikos\.cargo\registry\src\index.crates.io-6f17d22bba15001f\assert_cmd-2.0.16\src\assert.rs:158
   8: integration_tests::can_pass_input_to_command_from_a_file
             at .\tests\integration_tests.rs:305
   9: integration_tests::can_pass_input_to_command_from_a_file::closure$0
             at .\tests\integration_tests.rs:304
  10: core::ops::function::FnOnce::call_once<integration_tests::can_pass_input_to_command_from_a_file::closure_env$0,tuple$<> >
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:250
  11: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by ritvikos**
Tests using the `cat` command are specific to Unix-like environments and will fail on unsupported platforms.
Restrict these tests to unix environments only.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for reporting this and for opening a PR. It would be great if we could test this behavior on Windows somehow. Maybe we can find a Windows replacement for `cat`? Doesn't need to be a `cat`-equivalent. Just something that we can pass input *to*. And check if it received the input correctly.

**Comment by ritvikos** [comment]
Great idea!
Found that `type` is the replacement of `cat` in Windows.
Now the tests work fine 😄

- [Stackoverflow - Cat Replacement in Windows](https://stackoverflow.com/questions/60244/is-there-replacement-for-cat-on-windows)
- [Microsoft Docs - Type](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/type)

File: tests/integration_tests.rs [hunk 1]
```diff
@@ -312,6 +313,20 @@ fn can_pass_input_to_command_from_a_file() {
...
 }
 
+#[cfg(windows)]
+#[test]
+fn can_pass_input_to_command_from_a_file() {
+    hyperfine()
+        .arg("--runs=1")
+        .arg("--input=example_input_file.txt")
+        .arg("--show-output")
+        .arg("type example_input_file.txt")
```
Comment (sharkdp) [inline tests/integration_tests.rs:323]: This is not testing the right thing, I believe? The `cat` test above on Linux makes sure that we can pipe input from `example_input_file.txt` into the benchmarked command. But this looks to me like you ignore that and simply output the contents if `example_input_file.txt` using `type`.

**Comment by ritvikos** [comment]
[`type` cannot handle stdin like `cat`](https://superuser.com/questions/853580/real-windows-equivalent-to-cat-stdin#comment1574325_853608), just prints the content of the file.

Whoops! I missed that detail 😅
Nice catch!

Although, found 2 alternatives that can handle pipe stdin on Windows, 
let me know if you think it looks acceptable or you want me to look into other alternatives 😄 

1. `findstr x*`: [StackOverflow](https://superuser.com/questions/853580/real-windows-equivalent-to-cat-stdin)
> someprog | findstr x* or any other single character followed by 
> asterisk copies all lines from the pipe stdin to stdout.
```
~\Desktop\oss\hyperfine\tests> hyperfine --runs=1 --input=example_input_file.txt --show-output "findstr x*"
Benchmark 1: findstr x*
This text is part of a file
  Time (abs ≡):         21.8 ms               [User: 0.0 ms, System: 4.7 ms]
```

<br>

2. `more` command: Displays one screen of output at a time. 
[Microsoft - More](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/more) and [Unixtutorial.org](https://www.unixtutorial.org/commands/more) 
```
~\Desktop\oss\hyperfine\tests> hyperfine --runs=1 --input=example_input_file.txt --show-output "more"
Benchmark 1: more
This text is part of a file
  Time (abs ≡):         16.2 ms               [User: 0.0 ms, System: 5.9 ms]
```

**Comment by sharkdp** [comment]
> `findstr x*`: [StackOverflow](https://superuser.com/questions/853580/real-windows-equivalent-to-cat-stdin)

Thanks for looking into this. I think this is an acceptable hack. We should add a link to that stackoverflow answer to explain what's going on though.

**Comment by ritvikos** [comment]
Thank you for reviewing this. 
Fixed the issue and added the link as well.

**Comment by sharkdp** [comment]
Thank you. I think we can use something like `let command = if cfg!(windows) { … } else { … };` to merge the tests for windows and linux again, to remove some duplication.

**Comment by ritvikos** [comment]
That makes sense!
How about defining a `const` for platform-specific standard I/O utility (not sure about naming) with this approach? 🤔

**Comment by sharkdp** [comment]
Thank you!
